"""
opennote_service.py
────────────────────
Handles OpenNote API calls for Luma.

Lesson text is ALWAYS generated by Featherless directly — journals are
never searched or used for lesson content. OpenNote is only used here
for video generation.
"""

import os
import time
import json
from typing import Optional, TYPE_CHECKING
from dotenv import load_dotenv
from opennote import OpennoteClient
from models import LessonContent

if TYPE_CHECKING:
    from featherless_service import FeatherlessService

load_dotenv()

DEBUG_RAW_RESPONSE = True
DEFAULT_MODEL = "picasso"


class OpenNoteService:

    def __init__(self, api_key: str = None, featherless: "FeatherlessService" = None):
        self.api_key = api_key or os.getenv("OPENNOTE_API_KEY")
        if not self.api_key:
            raise ValueError("OpenNote API key not found. Set OPENNOTE_API_KEY in your .env file.")
        self.client     = OpennoteClient(api_key=self.api_key)
        self.featherless = featherless

    # ── Primary Method ────────────────────────────────────────────────────────

    def generate_lesson(
        self,
        topic: str,
        generate_video: bool = False,
        poll_interval: int = 5,
        timeout: int = 240,
    ) -> LessonContent:
        """
        Always generates lesson text via Featherless.
        Journals are never used — they caused unrelated content to appear.
        OpenNote is only called when generate_video=True.
        """
        print(f"[OpenNote] Generating lesson: '{topic}'")
        lesson = LessonContent(topic=topic, text="")

        # Always use Featherless for lesson text
        if self.featherless:
            print(f"[OpenNote] Asking Featherless to generate lesson text...")
            lesson.text = self.featherless.generate_lesson_text(topic)
        else:
            raise RuntimeError("FeatherlessService is required but not configured.")

        # Video is optional and only triggered on explicit request
        if generate_video:
            print(f"[OpenNote] Video requested — starting job (30-120s)...")
            try:
                result = self._create_video(topic, poll_interval, timeout)
                lesson.video_url = result.get("url")
                print(f"[OpenNote] Video URL: {lesson.video_url}")
            except Exception as e:
                print(f"[OpenNote] Video failed: {e} — continuing with text only")

        print(f"[OpenNote] Done — {lesson.summary()}")
        return lesson

    # ── Video ─────────────────────────────────────────────────────────────────

    def _create_video(self, topic: str, poll_interval: int, timeout: int) -> dict:
        video = self.client.video.create(
            model=DEFAULT_MODEL,
            messages=[{"role": "user", "content": topic}],
            include_sources=True,
            search_for=topic,
            source_count=3,
            upload_to_s3=True,
            title=f"Lesson: {topic[:50]}",
        )
        if DEBUG_RAW_RESPONSE:
            self._debug_print("video.create()", video)

        video_id = video.video_id
        elapsed  = 0

        while elapsed < timeout:
            status = self.client.video.status(video_id)

            if DEBUG_RAW_RESPONSE:
                self._debug_print(f"video.status() at {elapsed}s", status)

            job_status = getattr(status, "status", None)

            if job_status == "completed":
                url = self._extract_video_url(status)
                print(f"[OpenNote] Video completed. URL: {url}")
                return {"url": url}

            elif job_status == "failed":
                raise RuntimeError(f"Video job failed: {status}")

            print(f"[OpenNote] Video: '{job_status}' — retrying in {poll_interval}s...")
            time.sleep(poll_interval)
            elapsed += poll_interval

        raise TimeoutError(f"Video timed out after {timeout}s")

    def _extract_video_url(self, obj) -> Optional[str]:
        """Exhaustively searches the status object for a video URL."""
        url_fields = [
            "url", "video_url", "s3_url", "download_url", "stream_url",
            "video_link", "link", "src", "source", "path", "file_url",
            "media_url", "output_url", "result_url", "asset_url",
        ]
        for field in url_fields:
            val = getattr(obj, field, None)
            if val and isinstance(val, str) and val.startswith("http"):
                return val

        try:
            attrs = vars(obj) if hasattr(obj, "__dict__") else {}
        except Exception:
            attrs = {}

        for key, val in attrs.items():
            if isinstance(val, str) and val.startswith("http"):
                print(f"[OpenNote] Found URL in field '{key}': {val[:80]}")
                return val
            if isinstance(val, dict):
                nested = self._extract_video_url_from_dict(val)
                if nested:
                    return nested
            if hasattr(val, "__dict__") and val is not obj:
                nested = self._extract_video_url(val)
                if nested:
                    return nested

        return None

    def _extract_video_url_from_dict(self, d: dict) -> Optional[str]:
        for key, val in d.items():
            if isinstance(val, str) and val.startswith("http"):
                print(f"[OpenNote] Found URL in dict key '{key}': {val[:80]}")
                return val
            if isinstance(val, dict):
                nested = self._extract_video_url_from_dict(val)
                if nested:
                    return nested
        return None

    # ── Debug ─────────────────────────────────────────────────────────────────

    def _debug_print(self, label: str, obj) -> None:
        print(f"\n{'─' * 55}")
        print(f"[OpenNote DEBUG] {label}")
        try:
            print(json.dumps(obj.__dict__, indent=2, default=str))
        except Exception:
            print(repr(obj))
        print(f"{'─' * 55}\n")


# ── Quick Test ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    from featherless_service import FeatherlessService

    featherless = FeatherlessService()
    service     = OpenNoteService(featherless=featherless)

    print("=" * 55)
    print("TEST: Lesson via Featherless")
    print("=" * 55)
    lesson = service.generate_lesson("How does mitosis work?")
    print(f"\nText preview:\n{lesson.text[:400]}...")

    print("\n" + "=" * 55)
    print("TEST: Video (costs credits)")
    print("=" * 55)
    if input("Generate video? (y/n): ").strip().lower() == "y":
        lesson = service.generate_lesson("How does mitosis work?", generate_video=True)
        print(f"Video URL: {lesson.video_url}")
    else:
        print("Skipped.")

    print("\n✓ Done.")